// 工具配置文件 (Auto-generated by build.js)
// 包含跨域工具与 tools/ 目录下的所有应用。

const tools = [
    {
        "title": "Google Font to Svg Path",
        "description": "将 Google font 转换为 SVG path 的工具",
        "icon": "ri-font-family",
        "url": "https://fontsvg.ceda.is/",
        "tags": [
            "Font",
            "Google",
            "SVG"
        ]
    },
    {
        "title": "IT-Tools",
        "description": "为开发者和 IT 行业从业者准备的实用工具集合",
        "icon": "ri-tools-line",
        "url": "https://tools.ceda.is/",
        "tags": [
            "IT",
            "Google",
            "SVG"
        ]
    },
    {
        "title": "Base64 Encoder/Decoder",
        "description": "Free online tool to encode text and data to Base64 or decode Base64 back to text.",
        "icon": "ri-lock-unlock-line",
        "url": "/tools/base64-codec.html",
        "tags": [
            "Base64",
            "Encode",
            "Decode",
            "Security"
        ]
    },
    {
        "title": "BMI Calculator",
        "description": "Calculate your Body Mass Index (BMI) easily.",
        "icon": "ri-heart-pulse-line",
        "url": "/tools/bmi-calculator.html",
        "tags": [
            "BMI",
            "Health",
            "Calculator"
        ]
    },
    {
        "title": "Simple Calculator",
        "description": "A clean, simple online calculator.",
        "icon": "ri-calculator-line",
        "url": "/tools/calculator.html",
        "tags": [
            "Calculator",
            "Math",
            "Utility"
        ]
    },
    {
        "title": "Color Format Converter",
        "description": "Online color format converter. Convert between HEX, RGB, HSL, and more.",
        "icon": "ri-palette-line",
        "url": "/tools/color-converter.html",
        "tags": [
            "Color",
            "HEX",
            "RGB",
            "CSS",
            "Design"
        ]
    },
    {
        "title": "CSS Box Shadow Generator",
        "description": "Generate and preview CSS box shadows visually.",
        "icon": "ri-shape-2-line",
        "url": "/tools/css-shadow-generator.html",
        "tags": [
            "CSS",
            "Shadow",
            "Design",
            "Generator"
        ]
    },
    {
        "title": "Text Diff Checker",
        "description": "Compare two text snippets side by side and find the differences.",
        "icon": "ri-file-transfer-line",
        "url": "/tools/diff-checker.html",
        "tags": [
            "Diff",
            "Compare",
            "Text",
            "Developer Tools"
        ]
    },
    {
        "title": "EXIF Editor Pro",
        "description": "",
        "icon": "ri-image-edit-line",
        "url": "/tools/exif-editor.html",
        "tags": [
            "图像处理",
            "文字工具",
            "设计工具"
        ]
    },
    {
        "title": "Hash Generator",
        "description": "Generate MD5, SHA-1, SHA-256 and other hashes securely in-browser.",
        "icon": "ri-hashtag",
        "url": "/tools/hash-generator.html",
        "tags": [
            "Hash",
            "Crypto",
            "MD5",
            "SHA256",
            "Security"
        ]
    },
    {
        "title": "CodePreview - HTML实时预览工具",
        "description": "",
        "icon": "ri-code-line",
        "url": "/tools/html-renderer.html",
        "tags": [
            "HTML",
            "CSS",
            "JavaScript",
            "Editor",
            "Preview"
        ]
    },
    {
        "title": "图片蒙版工具",
        "description": "",
        "icon": "ri-image-circle-line",
        "url": "/tools/image-overlay-editor.html",
        "tags": [
            "图像处理",
            "文字工具",
            "设计工具"
        ]
    },
    {
        "title": "JSON Formatter & Validator",
        "description": "Free online tool to format, validate, and beautify JSON data.",
        "icon": "ri-brackets-line",
        "url": "/tools/json-formatter.html",
        "tags": [
            "JSON",
            "Formatter",
            "Developer Tools"
        ]
    },
    {
        "title": "JWT Decoder",
        "description": "Decode JSON Web Tokens (JWT) easily on the client-side.",
        "icon": "ri-key-2-line",
        "url": "/tools/jwt-decoder.html",
        "tags": [
            "JWT",
            "Security",
            "Token",
            "Decoder"
        ]
    },
    {
        "title": "Javascript Keycode Info",
        "description": "Press any key to get the JavaScript event keycode, code, and other properties.",
        "icon": "ri-keyboard-line",
        "url": "/tools/keycode-info.html",
        "tags": [
            "Keycode",
            "Javascript",
            "Events",
            "Keyboard"
        ]
    },
    {
        "title": "Lorem Ipsum Generator",
        "description": "Generate random placeholder text (Lorem Ipsum) for your designs.",
        "icon": "ri-text-line",
        "url": "/tools/lorem-ipsum.html",
        "tags": [
            "Lorem Ipsum",
            "Placeholder",
            "Design",
            "Text"
        ]
    },
    {
        "title": "MD App Generator",
        "description": "",
        "icon": "ri-markdown-line",
        "url": "/tools/markdown-builder.html",
        "tags": [
            "文字工具",
            "设计工具"
        ]
    },
    {
        "title": "Strong Password Generator",
        "description": "Generate secure, strong passwords instantly with custom parameters.",
        "icon": "ri-shield-keyhole-line",
        "url": "/tools/password-generator.html",
        "tags": [
            "Password",
            "Security",
            "Generator"
        ]
    },
    {
        "title": "Pomodoro Timer",
        "description": "A simple and effective Pomodoro technique timer.",
        "icon": "ri-timer-line",
        "url": "/tools/pomodoro-timer.html",
        "tags": [
            "Timer",
            "Pomodoro",
            "Productivity"
        ]
    },
    {
        "title": "QR Code Generator",
        "description": "Generate high-quality QR codes from text or URLs instantly.",
        "icon": "ri-qr-code-line",
        "url": "/tools/qr-generator.html",
        "tags": [
            "QR Code",
            "Generator",
            "Utility"
        ]
    },
    {
        "title": "Regex Tester",
        "description": "Test your regular expressions against target text in real-time.",
        "icon": "ri-code-block-line",
        "url": "/tools/regex-tester.html",
        "tags": [
            "Regex",
            "Developer Tools",
            "Matching"
        ]
    },
    {
        "title": "屏幕清理助手 - 纯黑全屏显示",
        "description": "在线屏幕清理助手，一键将屏幕切换为纯黑全屏模式，帮助您更清晰地发现和清理显示器上的灰尘、污渍和指纹。支持随时切换回纯白浅色背景。",
        "icon": "ri-computer-line",
        "url": "/tools/screen-cleaner.html",
        "tags": [
            "工具",
            "屏幕清理",
            "系统",
            "全屏"
        ]
    },
    {
        "title": "Stopwatch",
        "description": "Online stopwatch with split lap times.",
        "icon": "ri-stopwatch-line",
        "url": "/tools/stopwatch.html",
        "tags": [
            "Stopwatch",
            "Timer",
            "Time",
            "Utility"
        ]
    },
    {
        "title": "Word & Character Counter",
        "description": "Online text counter for words, characters, sentences, paragraphs, and reading time.",
        "icon": "ri-text-spacing",
        "url": "/tools/text-counter.html",
        "tags": [
            "Text",
            "Counter",
            "Writing",
            "SEO"
        ]
    },
    {
        "title": "Unix Timestamp Converter",
        "description": "Convert Unix timestamps to readable dates and vice versa.",
        "icon": "ri-time-line",
        "url": "/tools/timestamp-converter.html",
        "tags": [
            "Timestamp",
            "Unix",
            "Date",
            "Epoch",
            "Developer Tools"
        ]
    },
    {
        "title": "TraceIt - 图像矢量化工具",
        "description": "",
        "icon": "ri-image-line",
        "url": "/tools/traceIt.html",
        "tags": [
            "图像处理",
            "矢量化",
            "SVG",
            "设计工具"
        ]
    },
    {
        "title": "URL Encoder/Decoder",
        "description": "Free online tool to safely encode or decode URLs and URI query parameters.",
        "icon": "ri-links-line",
        "url": "/tools/url-codec.html",
        "tags": [
            "URL",
            "Encode",
            "Decode",
            "Developer Tools"
        ]
    },
    {
        "title": "UUID/GUID Generator",
        "description": "Generate random v4 UUIDs (Universally Unique Identifiers) instantly.",
        "icon": "ri-fingerprint-line",
        "url": "/tools/uuid-generator.html",
        "tags": [
            "UUID",
            "GUID",
            "Generator",
            "Developer Tools"
        ]
    },
    {
        "title": "微信公众号封面拼接工具",
        "description": "",
        "icon": "ri-wechat-line",
        "url": "/tools/wechat-cover-merge.html",
        "tags": [
            "微信",
            "图片",
            "合并",
            "封面",
            "公众号"
        ]
    }
];
